from __future__ import annotations
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field
import time
import uuid


class TaskStatus(str, Enum):
    pending = "pending"
    queued = "queued"
    running = "running"
    done = "done"
    failed = "failed"


class TaskCreate(BaseModel):
    prompt: str
    agent_id: Optional[str] = None  # None = auto-route by orchestrator
    model: Optional[str] = None


class Task(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    description: str
    prompt: str
    agent_id: Optional[str] = None
    status: TaskStatus = TaskStatus.queued
    progress: float = 0.0
    result: Optional[str] = None
    created_at: float = Field(default_factory=time.time)
    started_at: Optional[float] = None
    finished_at: Optional[float] = None
    tokens_generated: int = 0
    duration_ms: Optional[int] = None


class PlanTask(BaseModel):
    """A single step in a structured execution plan."""
    id: int
    action: str
    agent: str = "global"
    description: str = ""
    input_from: Optional[int] = None   # task id whose result feeds into this one
    depends_on: Optional[int] = None   # task id that must complete first
    output: Optional[str] = None
    status: TaskStatus = TaskStatus.pending
    retry: int = 0
    max_retry: int = 3
    result: Optional[str] = None
    error: Optional[str] = None


class TaskPlan(BaseModel):
    """Structured execution plan generated by the Global Agent."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    goal: str
    tasks: List[PlanTask] = Field(default_factory=list)
    created_at: float = Field(default_factory=time.time)
    status: TaskStatus = TaskStatus.pending
    iteration: int = 0
    max_iterations: int = 50
